/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent;

import advent.adventDayOne.CoordinateReader;

public class App {
    public String getGreeting() {
        CoordinateReader reader = new CoordinateReader();
        int sum = reader.coordinatesSum("app/src/main/resources/input.txt");
    
        System.out.println("Working Directory = " + System.getProperty("user.dir"));
        return "The sum is " + sum;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
